# Generated by Django 3.2.13 on 2022-06-13 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for uploaded data set', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name of training data set (e.g. Solar iradiaton data for West Africa)', max_length=200)),
                ('data_file', models.FileField(upload_to='uploads/')),
                ('description', models.TextField(default='', help_text='Give a brief desccription of data set you are uploading')),
                ('resp_colmn', models.CharField(default='response', help_text="Enter name of reponse column in data set or make sure a column in your data set is called 'response'", max_length=200, verbose_name='Response column name')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainedMLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for created ML model', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name of ML model', max_length=200)),
                ('model_file', models.FileField(upload_to='trained_models/')),
                ('description', models.TextField(default='', help_text='Say what the trained ML model does')),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
